name: ComandosDeComunicacion
main: muriplz.lel.ComandoMensaje
version: 2.3
api-version: 1.17
author: muriplz
description: La forma típica para comunicarse
commands:
  mensaje:
    description: manda un mensaje a un jugador.
    aliases: m
    permission: mensaje.mensaje
  responder:
    description: manda un mensaje al último jugador que te susurró.
    aliases: r
    permission: mensaje.responder