name: ComandoMensaje
main: muriplz.lel.ComandoMensaje
version: 2.2
api-version: 1.17
author: muriplz
commands:
  mensaje:
    description: manda un mensaje a un jugador.
    aliases: m
  responder:
    description: manda un mensaje al último jugador que te susurró.
    aliases: r